CREATE TABLE IF NOT EXISTS wms_fulfillment_order (
  id bigint NOT NULL AUTO_INCREMENT,
  tenant_id bigint NOT NULL DEFAULT 1,
  wms_tenant_id bigint NOT NULL,
  erp_tenant_id bigint NOT NULL,
  warehouse_id bigint NOT NULL,
  shop_id bigint NULL,
  fulfillment_no varchar(64) NOT NULL,
  source_type varchar(20) NOT NULL COMMENT 'OZON/WB/YANDEX/MANUAL',
  source_order_id bigint NOT NULL,
  source_order_no varchar(128) NOT NULL,
  platform_status varchar(64) NULL,
  fulfillment_status varchar(32) NOT NULL,
  recipient_name varchar(128) NULL,
  recipient_phone varchar(64) NULL,
  recipient_address varchar(1000) NULL,
  carrier_code varchar(64) NULL,
  carrier_name varchar(128) NULL,
  tracking_no varchar(128) NULL,
  package_weight_kg decimal(12,3) NULL,
  label_file_url varchar(1000) NULL,
  label_barcode varchar(255) NULL,
  label_fetched_time datetime NULL,
  label_verified_time datetime NULL,
  packed_time datetime NULL,
  shipped_time datetime NULL,
  cancel_reason varchar(500) NULL,
  version int NOT NULL DEFAULT 0,
  create_by bigint NULL,
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by bigint NULL,
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_fulfillment_no (fulfillment_no, deleted),
  UNIQUE KEY uk_fulfillment_source (source_type, source_order_id, deleted),
  KEY idx_fulfillment_workbench (warehouse_id, fulfillment_status, create_time),
  KEY idx_fulfillment_owner (erp_tenant_id, fulfillment_status, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='one-order-one-package warehouse fulfillment';

CREATE TABLE IF NOT EXISTS wms_fulfillment_item (
  id bigint NOT NULL AUTO_INCREMENT,
  fulfillment_order_id bigint NOT NULL,
  sku_code varchar(128) NOT NULL,
  warehouse_sku_code varchar(160) NOT NULL,
  sku_name varchar(500) NULL,
  image_url varchar(1000) NULL,
  quality varchar(32) NOT NULL DEFAULT 'GOOD',
  quantity int NOT NULL,
  picked_quantity int NOT NULL DEFAULT 0,
  outer_length_mm int NOT NULL,
  outer_width_mm int NOT NULL,
  outer_height_mm int NOT NULL,
  outer_gross_weight_g int NOT NULL,
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_fulfillment_item_sku (fulfillment_order_id, sku_code, quality, deleted),
  CONSTRAINT chk_fulfillment_item_qty CHECK (quantity > 0 AND picked_quantity >= 0 AND picked_quantity <= quantity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='immutable fulfillment item snapshot';

CREATE TABLE IF NOT EXISTS wms_inventory_reservation (
  id bigint NOT NULL AUTO_INCREMENT,
  fulfillment_order_id bigint NOT NULL,
  fulfillment_item_id bigint NULL,
  inventory_id bigint NOT NULL,
  location_id bigint NULL,
  quantity int NOT NULL,
  reservation_status varchar(20) NOT NULL DEFAULT 'RESERVED' COMMENT 'RESERVED/RELEASED/SHIPPED',
  version int NOT NULL DEFAULT 0,
  released_time datetime NULL,
  shipped_time datetime NULL,
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_fulfillment_reservation (fulfillment_order_id, inventory_id),
  KEY idx_reservation_inventory (inventory_id, reservation_status),
  CONSTRAINT chk_reservation_qty CHECK (quantity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='fulfillment to logical inventory reservation';

CREATE TABLE IF NOT EXISTS wms_fulfillment_platform_action (
  id bigint NOT NULL AUTO_INCREMENT,
  fulfillment_order_id bigint NOT NULL,
  action_type varchar(32) NOT NULL COMMENT 'ACCEPT/FETCH_LABEL/MARK_READY/FINALIZE',
  action_status varchar(32) NOT NULL COMMENT 'STARTED/SUCCEEDED/FAILED/RECONCILE_REQUIRED',
  request_fingerprint varchar(128) NOT NULL,
  request_payload longtext NULL,
  response_payload longtext NULL,
  error_message varchar(2000) NULL,
  attempt_count int NOT NULL DEFAULT 0,
  started_time datetime NULL,
  completed_time datetime NULL,
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_fulfillment_action (fulfillment_order_id, action_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='idempotent platform fulfillment actions';
