ALTER TABLE wms_adjustment_order
    MODIFY COLUMN order_status VARCHAR(20) NOT NULL DEFAULT 'PENDING_OWNER'
        COMMENT 'PENDING_OWNER/PENDING_DESTROY/SCRAPPED/REJECTED/CANCELLED',
    MODIFY COLUMN confirm_time DATETIME NULL COMMENT '海外仓实际销毁时间',
    MODIFY COLUMN confirm_by VARCHAR(64) NULL COMMENT '海外仓实际销毁操作人';
